# Generated by Django 5.2.3 on 2025-08-07 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pms', '0034_alter_reservation_check_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=100)),
                ('success', models.BooleanField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_logs', to='pms.room')),
            ],
            options={
                'verbose_name': 'Device Log',
                'verbose_name_plural': 'Device Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ESP32Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='ESP32 IP address (e.g., 192.168.1.100)')),
                ('mac_address', models.CharField(blank=True, help_text='MAC address of ESP32', max_length=17, unique=True)),
                ('firmware_version', models.CharField(blank=True, max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esp32', to='pms.room')),
            ],
            options={
                'verbose_name': 'ESP32 Device',
                'verbose_name_plural': 'ESP32 Devices',
            },
        ),
        migrations.CreateModel(
            name='RoomControls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_light_on', models.BooleanField(default=False)),
                ('rgb_light_on', models.BooleanField(default=False)),
                ('rgb_brightness', models.IntegerField(default=50, help_text='0-100')),
                ('rgb_red', models.IntegerField(default=255, help_text='0-255')),
                ('rgb_green', models.IntegerField(default=255, help_text='0-255')),
                ('rgb_blue', models.IntegerField(default=255, help_text='0-255')),
                ('ac_on', models.BooleanField(default=False)),
                ('ac_temperature', models.IntegerField(default=24, help_text='16-30°C')),
                ('ac_mode', models.CharField(choices=[('cool', 'Cool'), ('heat', 'Heat'), ('fan', 'Fan'), ('dry', 'Dry')], default='cool', max_length=10)),
                ('ac_fan_speed', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High'), ('auto', 'Auto')], default='auto', max_length=10)),
                ('reading_light_on', models.BooleanField(default=False)),
                ('bedside_light_on', models.BooleanField(default=False)),
                ('current_preset', models.CharField(choices=[('normal', 'Normal'), ('dark', 'Dark'), ('gloom', 'Gloom'), ('reading', 'Reading'), ('bedside', 'Bedside')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='pms.room')),
            ],
            options={
                'verbose_name': 'Room Controls',
                'verbose_name_plural': 'Room Controls',
            },
        ),
    ]
