# Generated by Django 5.2.3 on 2025-08-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_esp32configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32configuration',
            name='locker_endpoint',
            field=models.CharField(default='open/{locker_number}', help_text='Endpoint for locker control (use {locker_number} placeholder)', max_length=100),
        ),
        migrations.AddField(
            model_name='esp32configuration',
            name='locker_post_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional POST data for locker commands'),
        ),
        migrations.AddField(
            model_name='esp32device',
            name='auth_password',
            field=models.CharField(default='orcatech', help_text='Basic auth password', max_length=50),
        ),
        migrations.AddField(
            model_name='esp32device',
            name='auth_username',
            field=models.CharField(default='admin', help_text='Basic auth username', max_length=50),
        ),
    ]
