# Generated by Django 5.2.3 on 2025-08-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_esp32configuration_locker_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32configuration',
            name='alarm_disable_endpoint',
            field=models.CharField(default='alarm/disable', help_text='Endpoint for disabling alarm', max_length=100),
        ),
        migrations.AddField(
            model_name='esp32configuration',
            name='alarm_enable_endpoint',
            field=models.CharField(default='alarm/enable', help_text='Endpoint for enabling alarm', max_length=100),
        ),
        migrations.AddField(
            model_name='esp32configuration',
            name='alarm_post_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional POST data for alarm commands'),
        ),
        migrations.AddField(
            model_name='esp32configuration',
            name='alarm_set_endpoint',
            field=models.CharField(default='alarm/set', help_text='Endpoint for setting alarm', max_length=100),
        ),
        migrations.AddField(
            model_name='esp32configuration',
            name='mood_light_color_endpoint',
            field=models.CharField(default='light/mood/color', help_text='Endpoint for mood light color control', max_length=100),
        ),
        migrations.AddField(
            model_name='esp32configuration',
            name='mood_light_off_endpoint',
            field=models.CharField(default='light/mood/off', help_text='Endpoint for turning mood light OFF', max_length=100),
        ),
        migrations.AddField(
            model_name='esp32configuration',
            name='mood_light_on_endpoint',
            field=models.CharField(default='light/mood/on', help_text='Endpoint for turning mood light ON', max_length=100),
        ),
        migrations.AddField(
            model_name='esp32configuration',
            name='mood_light_post_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional POST data for mood light commands'),
        ),
        migrations.AddField(
            model_name='esp32configuration',
            name='outdoor_lights_off_endpoint',
            field=models.CharField(default='light/outdoor/off', help_text='Endpoint for turning outdoor lights OFF', max_length=100),
        ),
        migrations.AddField(
            model_name='esp32configuration',
            name='outdoor_lights_on_endpoint',
            field=models.CharField(default='light/outdoor/on', help_text='Endpoint for turning outdoor lights ON', max_length=100),
        ),
        migrations.AddField(
            model_name='esp32configuration',
            name='outdoor_lights_post_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional POST data for outdoor lights commands'),
        ),
        migrations.AddField(
            model_name='esp32configuration',
            name='scene_endpoint',
            field=models.CharField(default='scene/{scene_name}', help_text='Endpoint for scene control (use {scene_name} placeholder)', max_length=100),
        ),
        migrations.AddField(
            model_name='esp32configuration',
            name='scene_post_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional POST data for scene commands'),
        ),
        migrations.AddField(
            model_name='esp32configuration',
            name='spot_light_off_endpoint',
            field=models.CharField(default='light/spot/off', help_text='Endpoint for turning spot light OFF', max_length=100),
        ),
        migrations.AddField(
            model_name='esp32configuration',
            name='spot_light_on_endpoint',
            field=models.CharField(default='light/spot/on', help_text='Endpoint for turning spot light ON', max_length=100),
        ),
        migrations.AddField(
            model_name='esp32configuration',
            name='spot_light_post_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional POST data for spot light commands'),
        ),
        migrations.AddField(
            model_name='roomcontrols',
            name='alarm_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomcontrols',
            name='alarm_hour',
            field=models.IntegerField(default=7, help_text='0-23'),
        ),
        migrations.AddField(
            model_name='roomcontrols',
            name='alarm_minute',
            field=models.IntegerField(default=0, help_text='0-59'),
        ),
        migrations.AddField(
            model_name='roomcontrols',
            name='color_slider_position',
            field=models.FloatField(default=50.0, help_text='0.0-100.0'),
        ),
        migrations.AddField(
            model_name='roomcontrols',
            name='cooling_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomcontrols',
            name='current_scene',
            field=models.CharField(choices=[('bright', 'Bright'), ('dark', 'Dark'), ('gloomy', 'Gloomy'), ('movie', 'Movie')], default='bright', max_length=20),
        ),
        migrations.AddField(
            model_name='roomcontrols',
            name='mood_light_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomcontrols',
            name='outdoor_lights_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomcontrols',
            name='spot_light_on',
            field=models.BooleanField(default=False),
        ),
    ]
