# Generated by Django 5.2.3 on 2025-08-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_esp32configuration_alarm_disable_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp32device',
            name='mac_address',
            field=models.CharField(blank=True, help_text='MAC address of ESP32 (optional)', max_length=17, null=True),
        ),
    ]
