# Generated by Django 5.2.3 on 2025-08-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_remove_mac_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp32device',
            name='auth_password',
            field=models.CharField(blank=True, help_text='Basic auth password (optional)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='esp32device',
            name='auth_username',
            field=models.CharField(blank=True, help_text='Basic auth username (optional)', max_length=50, null=True),
        ),
    ]
