# Generated by Django 5.2.3 on 2025-06-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_alter_guest_email_alter_reservation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('expected_arrival', 'Expected Arrival'), ('expected_departure', 'Expected Departure'), ('canceled', 'Canceled'), ('no_show', 'No-Show')], default='pending', max_length=20),
        ),
    ]
