# Generated by Django 5.2.3 on 2025-07-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_reservation_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
