# Generated by Django 5.2.3 on 2025-07-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_reservation_payment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='guest',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='guest',
            name='id_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='num_guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('expected_arrival', 'Expected Arrival'), ('checked_in', 'Checked In'), ('in_house', 'In House'), ('expected_departure', 'Expected Departure'), ('checked_out', 'Checked Out'), ('canceled', 'Canceled'), ('no_show', 'No-Show')], default='pending', max_length=20),
        ),
    ]
