# Generated by Django 5.2.3 on 2025-07-11 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_guest_address_guest_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earliest_check_in_time', models.TimeField(default=datetime.time(14, 0))),
                ('latest_check_in_time', models.TimeField(default=datetime.time(22, 0))),
                ('check_in_grace_period', models.IntegerField(default=0, help_text='Grace period in minutes')),
            ],
            options={
                'verbose_name': 'Hotel Settings',
                'verbose_name_plural': 'Hotel Settings',
            },
        ),
    ]
