# Generated by Django 5.2.3 on 2025-07-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0007_hotelsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('vacant_clean', 'Vacant Clean'), ('vacant_dirty', 'Vacant Dirty'), ('occupied', 'Occupied'), ('out_of_order', 'Out of Order'), ('maintenance', 'Maintenance')], default='vacant_clean', max_length=20),
        ),
    ]
