# Generated by Django 5.2.3 on 2025-07-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0009_reservation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
