# Generated by Django 5.2.3 on 2025-07-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0010_reservation_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('expected_arrival', 'Expected Arrival'), ('in_house', 'In House'), ('expected_departure', 'Expected Departure'), ('checked_out', 'Checked Out'), ('canceled', 'Canceled'), ('no_show', 'No-Show')], default='pending', max_length=20),
        ),
    ]
