# Generated by Django 5.2.3 on 2025-07-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0012_alter_guest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='agent',
            field=models.CharField(choices=[('direct', 'Direct Booking'), ('booking_com', 'Booking.com'), ('expedia', 'Expedia'), ('agoda', 'Agoda'), ('airbnb', 'Airbnb'), ('travel_agent', 'Travel Agent'), ('corporate', 'Corporate'), ('walk_in', 'Walk-in'), ('phone', 'Phone Booking'), ('other', 'Other')], default='direct', help_text='Source/agent where this reservation came from', max_length=20),
        ),
    ]
