# Generated by Django 5.2.3 on 2025-07-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0014_reservation_base_amount_reservation_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('garden_view', 'Garden View'), ('mountain_view', 'Mountain View')], max_length=20),
        ),
    ]
