# Generated by Django 5.2.3 on 2025-07-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0017_alter_guest_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='id_type',
            field=models.CharField(blank=True, choices=[('', 'Select ID Type'), ('passport', 'Passport'), ('ktp', 'KTP (Indonesian ID)'), ('drivers_license', "Driver's License"), ('national_id', 'National ID Card'), ('sim', "SIM (Indonesian Driver's License)"), ('visa', 'Visa'), ('other', 'Other')], help_text='Type of identification document', max_length=50),
        ),
    ]
