# Generated by Django 5.2.3 on 2025-07-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0018_alter_guest_id_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nationality name (e.g., Indonesian, American)', max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='Optional country code (e.g., ID, US)', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this nationality is available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nationality',
                'verbose_name_plural': 'Nationalities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='guest',
            name='nationality_new',
            field=models.ForeignKey(blank=True, help_text="Guest's nationality (new)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.nationality'),
        ),
    ]
