# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.db import migrations

def populate_nationalities_and_migrate_data(apps, schema_editor):
    Nationality = apps.get_model('pms', 'Nationality')
    Guest = apps.get_model('pms', 'Guest')
    
    # Create nationality mapping
    nationality_mapping = {
        'indonesian': {'name': 'Indonesian', 'code': 'ID'},
        'american': {'name': 'American', 'code': 'US'},
        'australian': {'name': 'Australian', 'code': 'AU'},
        'british': {'name': 'British', 'code': 'GB'},
        'canadian': {'name': 'Canadian', 'code': 'CA'},
        'chinese': {'name': 'Chinese', 'code': 'CN'},
        'dutch': {'name': 'Dutch', 'code': 'NL'},
        'french': {'name': 'French', 'code': 'FR'},
        'german': {'name': 'German', 'code': 'DE'},
        'indian': {'name': 'Indian', 'code': 'IN'},
        'japanese': {'name': 'Japanese', 'code': 'JP'},
        'malaysian': {'name': 'Malaysian', 'code': 'MY'},
        'singaporean': {'name': 'Singaporean', 'code': 'SG'},
        'south_korean': {'name': 'South Korean', 'code': 'KR'},
        'thai': {'name': 'Thai', 'code': 'TH'},
        'vietnamese': {'name': 'Vietnamese', 'code': 'VN'},
        'other': {'name': 'Other', 'code': ''},
    }
    
    # Add more common nationalities
    additional_nationalities = [
        {'name': 'Italian', 'code': 'IT'},
        {'name': 'Spanish', 'code': 'ES'},
        {'name': 'Portuguese', 'code': 'PT'},
        {'name': 'Brazilian', 'code': 'BR'},
        {'name': 'Mexican', 'code': 'MX'},
        {'name': 'Russian', 'code': 'RU'},
        {'name': 'Swiss', 'code': 'CH'},
        {'name': 'Swedish', 'code': 'SE'},
        {'name': 'Norwegian', 'code': 'NO'},
        {'name': 'Danish', 'code': 'DK'},
        {'name': 'Finnish', 'code': 'FI'},
        {'name': 'Belgian', 'code': 'BE'},
        {'name': 'Austrian', 'code': 'AT'},
        {'name': 'New Zealand', 'code': 'NZ'},
        {'name': 'South African', 'code': 'ZA'},
    ]
    
    # Create nationality objects
    nationality_objects = {}
    
    # Create from mapping
    for key, data in nationality_mapping.items():
        nationality, created = Nationality.objects.get_or_create(
            name=data['name'],
            defaults={'code': data['code']}
        )
        nationality_objects[key] = nationality
    
    # Create additional nationalities
    for data in additional_nationalities:
        Nationality.objects.get_or_create(
            name=data['name'],
            defaults={'code': data['code']}
        )
    
    # Migrate existing guest data
    for guest in Guest.objects.all():
        if guest.nationality and guest.nationality in nationality_objects:
            guest.nationality_new = nationality_objects[guest.nationality]
            guest.save()

def reverse_populate_nationalities(apps, schema_editor):
    Nationality = apps.get_model('pms', 'Nationality')
    Guest = apps.get_model('pms', 'Guest')
    
    # Clear the new nationality field
    Guest.objects.update(nationality_new=None)
    
    # Delete all nationalities
    Nationality.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0019_nationality_guest_nationality_new'),
    ]

    operations = [
        migrations.RunPython(populate_nationalities_and_migrate_data, reverse_populate_nationalities),
    ]