# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0020_populate_nationalities_and_migrate_data'),
    ]

    operations = [
        # Step 1: Remove the old nationality CharField
        migrations.RemoveField(
            model_name='guest',
            name='nationality',
        ),
        # Step 2: Rename nationality_new to nationality
        migrations.RenameField(
            model_name='guest',
            old_name='nationality_new',
            new_name='nationality',
        ),
    ]