# Generated by Django 5.2.3 on 2025-07-26 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0021_finalize_nationality_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Payment method name (e.g., Bank Transfer, Cash)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Internal code for the payment method', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description or instructions')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is available for selection')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display this payment method')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='guest',
            name='nationality',
            field=models.ForeignKey(blank=True, help_text="Guest's nationality", null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.nationality'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method_new',
            field=models.ForeignKey(blank=True, help_text='Payment method used for this reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.paymentmethod'),
        ),
    ]
