# Generated by Django 5.2.3 on 2025-07-26 06:30

from django.db import migrations


def populate_payment_methods(apps, schema_editor):
    """Populate PaymentMethod table with existing payment method choices."""
    PaymentMethod = apps.get_model('pms', 'PaymentMethod')
    
    payment_methods = [
        {'name': 'Bank Transfer', 'code': 'bank_transfer', 'description': 'Payment via bank transfer', 'display_order': 1},
        {'name': 'Cash', 'code': 'cash', 'description': 'Cash payment', 'display_order': 2},
        {'name': 'Credit Card', 'code': 'credit_card', 'description': 'Payment via credit card', 'display_order': 3},
    ]
    
    for method_data in payment_methods:
        PaymentMethod.objects.get_or_create(
            code=method_data['code'],
            defaults={
                'name': method_data['name'],
                'description': method_data['description'],
                'display_order': method_data['display_order'],
                'is_active': True,
            }
        )


def reverse_populate_payment_methods(apps, schema_editor):
    """Remove populated payment methods."""
    PaymentMethod = apps.get_model('pms', 'PaymentMethod')
    PaymentMethod.objects.filter(
        code__in=['bank_transfer', 'cash', 'credit_card']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0022_paymentmethod_alter_guest_nationality_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_payment_methods, reverse_populate_payment_methods),
    ]
