# Generated by Django 5.2.3 on 2025-07-26 06:34

from django.db import migrations


def copy_payment_method_data(apps, schema_editor):
    """Copy payment method data from old field to new field"""
    Reservation = apps.get_model('pms', 'Reservation')
    PaymentMethod = apps.get_model('pms', 'PaymentMethod')
    
    # Mapping from old payment method codes to new PaymentMethod objects
    payment_method_mapping = {
        'bank_transfer': PaymentMethod.objects.get(code='bank_transfer'),
        'cash': PaymentMethod.objects.get(code='cash'),
        'credit_card': PaymentMethod.objects.get(code='credit_card'),
    }
    
    # Update all reservations
    for reservation in Reservation.objects.all():
        if reservation.payment_method in payment_method_mapping:
            reservation.payment_method_new = payment_method_mapping[reservation.payment_method]
            reservation.save()


def reverse_copy_payment_method_data(apps, schema_editor):
    """Reverse the payment method data copy"""
    Reservation = apps.get_model('pms', 'Reservation')
    
    # Mapping from PaymentMethod objects back to old codes
    reverse_mapping = {
        'Bank Transfer': 'bank_transfer',
        'Cash': 'cash',
        'Credit Card': 'credit_card',
    }
    
    # Update all reservations
    for reservation in Reservation.objects.all():
        if reservation.payment_method_new and reservation.payment_method_new.name in reverse_mapping:
            reservation.payment_method = reverse_mapping[reservation.payment_method_new.name]
            reservation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0023_auto_20250726_1330'),
    ]

    operations = [
        migrations.RunPython(copy_payment_method_data, reverse_copy_payment_method_data),
    ]
