# Generated by Django 5.2.3 on 2025-07-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0024_copy_payment_method_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='payment_method',
        ),
    ]
