# Generated by Django 5.2.3 on 2025-07-26 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0026_rename_payment_method_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the booking agent/source', max_length=100, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which this agent appears in dropdowns')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this agent is currently available for selection')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='agent_new',
            field=models.ForeignKey(blank=True, help_text='Booking agent/source for this reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.agent'),
        ),
    ]
