# Generated by Django 5.2.3 on 2025-07-26 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0031_agent_created_at_agent_updated_at_alter_agent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications_enabled', models.BooleanField(default=False, help_text='Enable or disable email notifications globally')),
                ('send_pending_notifications', models.BooleanField(default=True, help_text='Send email when reservation is created with pending status')),
                ('send_confirmed_notifications', models.BooleanField(default=True, help_text='Send email when reservation is confirmed')),
                ('send_expected_arrival_notifications', models.BooleanField(default=True, help_text='Send email when guest is expected to arrive')),
                ('send_expected_departure_notifications', models.BooleanField(default=True, help_text='Send email when guest is expected to depart')),
                ('hotel_name', models.CharField(default='Bird Nest PMS', help_text='Hotel name to display in emails', max_length=200)),
                ('hotel_contact', models.CharField(blank=True, help_text='Hotel contact information for emails', max_length=200)),
                ('hotel_address', models.TextField(blank=True, help_text='Hotel address for emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Notification Settings',
                'verbose_name_plural': 'Email Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('expected_arrival', 'Expected Arrival'), ('expected_departure', 'Expected Departure')], max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='pms.reservation')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
