# Generated by Django 5.2.3 on 2025-07-27 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0032_emailnotificationsettings_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.TextField(blank=True, help_text='Room amenities (comma-separated)'),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, help_text='Room description'),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(blank=True, help_text='Floor number', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='has_ac',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_minibar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_tv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='has_wifi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='housekeeping_notes',
            field=models.TextField(blank=True, help_text='Special housekeeping instructions'),
        ),
        migrations.AddField(
            model_name='room',
            name='last_cleaned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='maintenance_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='maintenance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='maintenance_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='max_occupancy',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of guests'),
        ),
        migrations.AddField(
            model_name='room',
            name='size_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Room size in square meters', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='status_changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='status_changed_by',
            field=models.CharField(blank=True, help_text='Who changed the status', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='status_reason',
            field=models.TextField(blank=True, help_text='Reason for status change'),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('vacant_clean', 'Vacant Clean'), ('vacant_dirty', 'Vacant Dirty'), ('occupied', 'Occupied'), ('out_of_order', 'Out of Order'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], default='vacant_clean', max_length=20),
        ),
        migrations.CreateModel(
            name='RoomMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('scheduled', 'Scheduled Maintenance'), ('emergency', 'Emergency Repair'), ('out_of_order', 'Out of Order'), ('deep_cleaning', 'Deep Cleaning'), ('renovation', 'Renovation'), ('inspection', 'Inspection')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor', models.CharField(blank=True, help_text='Maintenance vendor/contractor', max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='pms.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
