# Generated by Django 5.2.3 on 2025-08-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0033_room_amenities_room_created_at_room_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('vacant_clean', 'Vacant Clean'), ('vacant_dirty', 'Vacant Dirty'), ('occupied', 'Occupied'), ('out_of_order', 'Out of Order'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], db_index=True, default='vacant_clean', max_length=20),
        ),
    ]
