# Generated by Django 5.2.3 on 2025-07-27 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0034_attractioninfo_roomdevicestate_tabletcontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESP32ButtonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_light_enabled', models.BooleanField(default=True, help_text='Enable/disable front light button')),
                ('front_light_endpoint', models.CharField(default='/front_light', help_text='ESP32 endpoint for front light', max_length=100)),
                ('front_light_on_command', models.CharField(default='on', help_text='Command to turn on front light', max_length=50)),
                ('front_light_off_command', models.CharField(default='off', help_text='Command to turn off front light', max_length=50)),
                ('back_light_enabled', models.BooleanField(default=True, help_text='Enable/disable back light button')),
                ('back_light_endpoint', models.CharField(default='/back_light', help_text='ESP32 endpoint for back light', max_length=100)),
                ('back_light_on_command', models.CharField(default='on', help_text='Command to turn on back light', max_length=50)),
                ('back_light_off_command', models.CharField(default='off', help_text='Command to turn off back light', max_length=50)),
                ('main_light_enabled', models.BooleanField(default=True, help_text='Enable/disable main light button')),
                ('main_light_endpoint', models.CharField(default='/main_light', help_text='ESP32 endpoint for main light', max_length=100)),
                ('main_light_on_command', models.CharField(default='on', help_text='Command to turn on main light', max_length=50)),
                ('main_light_off_command', models.CharField(default='off', help_text='Command to turn off main light', max_length=50)),
                ('sport_light_enabled', models.BooleanField(default=True, help_text='Enable/disable sport light button')),
                ('sport_light_endpoint', models.CharField(default='/sport_light', help_text='ESP32 endpoint for sport light', max_length=100)),
                ('sport_light_on_command', models.CharField(default='on', help_text='Command to turn on sport light', max_length=50)),
                ('sport_light_off_command', models.CharField(default='off', help_text='Command to turn off sport light', max_length=50)),
                ('rgb_light_enabled', models.BooleanField(default=True, help_text='Enable/disable RGB light controls')),
                ('rgb_endpoint', models.CharField(default='/rgb', help_text='ESP32 endpoint for RGB light', max_length=100)),
                ('ac_enabled', models.BooleanField(default=True, help_text='Enable/disable AC controls')),
                ('ac_endpoint', models.CharField(default='/ac', help_text='ESP32 endpoint for AC', max_length=100)),
                ('status_endpoint', models.CharField(default='/status', help_text='ESP32 endpoint to get device status', max_length=100)),
                ('timeout_seconds', models.IntegerField(default=5, help_text='Request timeout in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esp32_config', to='pms.room')),
            ],
            options={
                'verbose_name': 'ESP32 Button Configuration',
                'verbose_name_plural': 'ESP32 Button Configurations',
            },
        ),
    ]
