# Generated by Django 5.2.3 on 2025-06-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Not Specified'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('credit_card', 'Credit Card')], default='', max_length=20),
        ),
    ]
